name: Build macOS .app

on:
  push:
    tags:
      - 'v1.1.*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .app using PyInstaller
        run: |
          pyinstaller main.py \
            --noconfirm \
            --windowed \
            --name "FPA" \
            --icon "assets/fpa_icon.icns" \
            --target-arch arm64 \
            --target-arch x86_64 \
            --add-data "UI/fpa_data_coll_exe.ui:UI" \
            --add-data "assets/football_field.png:assets" \
            --add-data "assets/logo.png:assets" \
            --add-data "assets/statguide.png:assets"
          main.py

      - name: Upload macOS .app
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/*.app