name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build app
        run: |
          pyinstaller --onefile --windowed \
            --add-data "UI/fpa_data_coll_exe.ui:UI" \
            --add-data "assets/football_field.png:assets" \
            --add-data "assets/logo.png:assets" \
            --add-data "assets/statguide.png:assets" \
            --add-data "assets/fpa_icon.icns:assets" \
            main.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app
          path: dist/main
