name: Build Windows .exe

on:
  push:
    tags:
      - 'v1.0.*'

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PYTHONUTF8: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .exe using PyInstaller
        run: |
          pyinstaller --name fpa --icon "assets/fpa_icon.ico" --noconfirm --onefile --windowed --collect-all pandas --collect-all PyQt5 --hidden-import openpyxl --add-data "UI/fpa_data_coll_exe.ui;UI" --add-data "assets/football_field.png;assets" --add-data "assets/logo.png;assets" --add-data "assets/statguide.png;assets" main.py

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: fpa-windows-exe-${{ github.ref_name }}
          path: dist/fpa.exe